from google.adk.agents import SequentialAgent, LoopAgent

from .sub_agents.planner.planning_agent import planning_agent
from .sub_agents.coder.coding_agent import coding_agent


# # Create the Refinement Loop Agent
# loop_agent = LoopAgent(
#     name="loop_agent",
#     max_iterations=10,
#     sub_agents=[
#         coding_agent,
#         # building_agent,
#         # testing_agent,
#         # deployment_agent,
#         # rollback_agent,
#     ],
#     description="Refines the code generated by the Coding Agent based on testing and feedback",
# )

# Create the Root Sequential Agent
root_agent = SequentialAgent(
    name="root_agent",
    sub_agents=[
        planning_agent,
        coding_agent,
        # loop_agent,
        # insights_agent,
        # escalation_agent,
        # monitoring_agent,
    ],
    description="Organizes an automatic, end-to-end DevOps pipeline",
)
